# Generated by Django 5.1.4 on 2024-12-26 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dictionary", "0001_initial"),
        ("languages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="definitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="definition",
            name="lang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="definitions",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="historicaldefinition",
            name="contributor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldefinition",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldefinition",
            name="lang",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="historicalword",
            name="contributor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalword",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalword",
            name="lang",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dict_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="lang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dict_entries",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="historicaldefinition",
            name="dict_entry",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dictionary.word",
            ),
        ),
        migrations.AddField(
            model_name="definition",
            name="dict_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="definitions",
                to="dictionary.word",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="word",
            unique_together={("word", "lang")},
        ),
        migrations.AlterUniqueTogether(
            name="definition",
            unique_together={("dict_entry", "lang", "description")},
        ),
    ]
