# Generated by Django 5.1.4 on 2025-01-29 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dictionary", "0001_initial"),
        ("languages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="contributor",
            field=models.ForeignKey(
                help_text="The user who contributed this definition.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="definitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="definition",
            name="lang",
            field=models.ForeignKey(
                help_text="The language of this definition.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="definitions",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="historicaldefinition",
            name="contributor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The user who contributed this definition.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldefinition",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldefinition",
            name="lang",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The language of this definition.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="historicalword",
            name="contributor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The user who contributed this word.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalword",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalword",
            name="lang",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The language of this word.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="historicaldefinition",
            name="pos",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The part of speech for this definition (e.g., noun, verb).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dictionary.partofspeech",
            ),
        ),
        migrations.AddField(
            model_name="definition",
            name="pos",
            field=models.ForeignKey(
                blank=True,
                help_text="The part of speech for this definition (e.g., noun, verb).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="definitions",
                to="dictionary.partofspeech",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="contributor",
            field=models.ForeignKey(
                help_text="The user who contributed this word.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="words",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="lang",
            field=models.ForeignKey(
                help_text="The language of this word.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="words",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="historicaldefinition",
            name="word",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The word for which this definition applies.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dictionary.word",
            ),
        ),
        migrations.AddField(
            model_name="definition",
            name="antonyms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Antonyms for the word.",
                related_name="indirect_antonyms",
                to="dictionary.word",
            ),
        ),
        migrations.AddField(
            model_name="definition",
            name="synonyms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Synonyms for the word.",
                related_name="indirect_synonyms",
                to="dictionary.word",
            ),
        ),
        migrations.AddField(
            model_name="definition",
            name="word",
            field=models.ForeignKey(
                help_text="The word for which this definition applies.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="definitions",
                to="dictionary.word",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="word",
            unique_together={("word", "lang")},
        ),
        migrations.AlterUniqueTogether(
            name="definition",
            unique_together={("word", "lang", "description")},
        ),
    ]
