# Generated by Django 5.1.4 on 2025-01-10 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartOfSpeech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbr", models.CharField(max_length=8, unique=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="definition",
            name="pos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="definitions",
                to="dictionary.partofspeech",
            ),
        ),
        migrations.AddField(
            model_name="historicaldefinition",
            name="pos",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dictionary.partofspeech",
            ),
        ),
    ]
