# Generated by Django 5.1.4 on 2025-01-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0003_partofspeech_definition_pos_historicaldefinition_pos"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="source_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="definition",
            name="source_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="definition",
            name="usage_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldefinition",
            name="source_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldefinition",
            name="source_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaldefinition",
            name="usage_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
