# Generated by Django 5.1.4 on 2025-01-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0005_historicalword_source_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="antonyms",
            field=models.ManyToManyField(
                blank=True, related_name="indirect_antonyms", to="dictionary.word"
            ),
        ),
        migrations.AddField(
            model_name="definition",
            name="synonyms",
            field=models.ManyToManyField(
                blank=True, related_name="indirect_synonyms", to="dictionary.word"
            ),
        ),
    ]
