# Generated by Django 5.1.6 on 2025-02-25 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("languages", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WordleGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_length", models.IntegerField(default=5)),
                ("max_guesses", models.IntegerField(default=6)),
                ("solution", models.CharField(max_length=5)),
                ("guesses", models.JSONField(default=list)),
                (
                    "game_status",
                    models.CharField(
                        choices=[
                            ("playing", "Playing"),
                            ("win", "Win"),
                            ("lose", "Lose"),
                        ],
                        default="playing",
                        max_length=7,
                    ),
                ),
                ("date_start", models.DateTimeField(auto_now_add=True)),
                ("date_end", models.DateTimeField(auto_now=True)),
                (
                    "lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wordle_games",
                        to="languages.language",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wordle_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
