# Generated by Django 5.1.4 on 2025-01-29 04:11

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the category.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the category.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="HistoricalPhrase",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The phrase content.", max_length=10000),
                ),
                (
                    "usage_note",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes on the usage of the phrase.",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "source_title",
                    models.CharField(
                        blank=True,
                        help_text="The title of the source.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "source_link",
                    models.URLField(
                        blank=True,
                        help_text="A link to the source of the phrase.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Phrase",
                "verbose_name_plural": "historical Phrases",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTranslation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The translated phrase content.", max_length=10000
                    ),
                ),
                (
                    "source_title",
                    models.CharField(
                        blank=True,
                        help_text="The title of the source.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "source_link",
                    models.URLField(
                        blank=True,
                        help_text="A link to the source of the translation.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Translation",
                "verbose_name_plural": "historical Translations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Phrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The phrase content.", max_length=10000),
                ),
                (
                    "usage_note",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes on the usage of the phrase.",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "source_title",
                    models.CharField(
                        blank=True,
                        help_text="The title of the source.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "source_link",
                    models.URLField(
                        blank=True,
                        help_text="A link to the source of the phrase.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Phrase",
                "verbose_name_plural": "Phrases",
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The translated phrase content.", max_length=10000
                    ),
                ),
                (
                    "source_title",
                    models.CharField(
                        blank=True,
                        help_text="The title of the source.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "source_link",
                    models.URLField(
                        blank=True,
                        help_text="A link to the source of the translation.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Translation",
                "verbose_name_plural": "Translations",
            },
        ),
    ]
