# Generated by Django 5.1.4 on 2024-12-26 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("languages", "0002_initial"),
        ("phrases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphrase",
            name="contributor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalphrase",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalphrase",
            name="lang",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="historicaltranslation",
            name="contributor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaltranslation",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaltranslation",
            name="lang",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="phrase_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="lang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="phrase_entries",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="historicaltranslation",
            name="phrase_entry",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="phrases.phrase",
            ),
        ),
        migrations.AddField(
            model_name="translation",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="translations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="translation",
            name="lang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="translations",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="translation",
            name="phrase_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="phrases.phrase",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="phrase",
            unique_together={("content", "lang")},
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together={("content", "lang", "phrase_entry")},
        ),
    ]
