# Generated by Django 5.1.4 on 2025-01-29 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("languages", "0002_initial"),
        ("phrases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphrase",
            name="contributor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The user who contributed this phrase.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalphrase",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalphrase",
            name="lang",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The language this phrase belongs to.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="historicaltranslation",
            name="contributor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The user who contributed this translation.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaltranslation",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaltranslation",
            name="lang",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The language of the translation.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="categories",
            field=models.ManyToManyField(
                help_text="Categories associated with this phrase.",
                related_name="phrases",
                to="phrases.category",
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="contributor",
            field=models.ForeignKey(
                help_text="The user who contributed this phrase.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="phrases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="lang",
            field=models.ForeignKey(
                help_text="The language this phrase belongs to.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="phrases",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="historicaltranslation",
            name="phrase",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The phrase being translated.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="phrases.phrase",
            ),
        ),
        migrations.AddField(
            model_name="translation",
            name="contributor",
            field=models.ForeignKey(
                help_text="The user who contributed this translation.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="translations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="translation",
            name="lang",
            field=models.ForeignKey(
                help_text="The language of the translation.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="translations",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="translation",
            name="phrase",
            field=models.ForeignKey(
                help_text="The phrase being translated.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="phrases.phrase",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="phrase",
            unique_together={("content", "lang")},
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together={("content", "lang", "phrase")},
        ),
    ]
