# Generated by Django 5.1.4 on 2024-12-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phrases", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalphrase",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical phrase",
                "verbose_name_plural": "historical phrases",
            },
        ),
    ]
