# Generated by Django 5.1.4 on 2025-01-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phrases", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="phrase",
            name="categories",
            field=models.ManyToManyField(related_name="phrases", to="phrases.category"),
        ),
    ]
