# Generated by Django 5.1.4 on 2025-01-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phrases", "0003_category_phrase_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphrase",
            name="source_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalphrase",
            name="source_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="phrase",
            name="source_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phrase",
            name="source_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
