# Generated by Django 5.1.4 on 2025-01-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phrases", "0004_historicalphrase_source_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphrase",
            name="usage_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phrase",
            name="usage_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
