# Generated by Django 5.1.4 on 2025-01-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phrases", "0005_historicalphrase_usage_note_phrase_usage_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltranslation",
            name="source_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltranslation",
            name="source_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="translation",
            name="source_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="translation",
            name="source_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
