# Generated by Django 5.1.1 on 2024-11-08 15:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_languageproficiency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="languageproficiency",
            old_name="language",
            new_name="lang",
        ),
        migrations.RenameField(
            model_name="languageproficiency",
            old_name="proficiency_level",
            new_name="level",
        ),
        migrations.AlterUniqueTogether(
            name="languageproficiency",
            unique_together={("user", "lang")},
        ),
    ]
