# Generated by Django 5.1.1 on 2024-11-22 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="languageproficiency",
            name="lang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proficiencies",
                to="content.language",
            ),
        ),
    ]
