# Generated by Django 5.1.1 on 2024-12-21 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_alter_languageproficiency_lang"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vote",
            name="unique_textentry_vote",
        ),
        migrations.RemoveConstraint(
            model_name="vote",
            name="unique_translation_vote",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="text_entry",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="translation",
        ),
        migrations.AddField(
            model_name="vote",
            name="content_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vote",
            name="object_id",
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
