# Generated by Django 5.1.1 on 2024-12-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_remove_vote_unique_textentry_vote_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaltextentry",
            old_name="author",
            new_name="contributor",
        ),
        migrations.RenameField(
            model_name="historicaltranslation",
            old_name="author",
            new_name="contributor",
        ),
        migrations.RenameField(
            model_name="textentry",
            old_name="author",
            new_name="contributor",
        ),
        migrations.RenameField(
            model_name="translation",
            old_name="author",
            new_name="contributor",
        ),
    ]
