# Generated by Django 5.1.1 on 2024-11-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_bio_user_date_of_birth_user_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("", "Prefer not to say"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
