# Generated by Django 5.1.4 on 2025-01-29 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="The ID of the object being voted on."
                    ),
                ),
                (
                    "value",
                    models.SmallIntegerField(
                        choices=[(1, "Upvote"), (-1, "Downvote"), (0, "Unvote")],
                        help_text="The type of vote: Upvote (1), Downvote (-1), or Unvote (0).",
                    ),
                ),
                (
                    "voted_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the vote was last modified.",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The content type of the object being voted on.",
                        limit_choices_to={
                            "model__in": ["phrase", "word", "translation", "definition"]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vote",
                "verbose_name_plural": "Votes",
            },
        ),
    ]
