# Generated by Django 5.1.4 on 2024-12-26 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=32)),
            ],
            options={
                "unique_together": {("code", "name")},
            },
        ),
        migrations.CreateModel(
            name="LanguageProficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Elementary Proficiency"),
                            (2, "Limited Working Proficiency"),
                            (3, "Professional Working Proficiency"),
                            (4, "Full Professional Proficiency"),
                            (5, "Native / Bilingual Proficiency"),
                        ]
                    ),
                ),
                (
                    "lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proficiencies",
                        to="languages.language",
                    ),
                ),
            ],
        ),
    ]
