# Generated by Django 5.1.4 on 2025-01-29 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="The unique code for the language (e.g., 'eng' for English).",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The full name of the language (e.g., 'English').",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "unique_together": {("code", "name")},
            },
        ),
        migrations.CreateModel(
            name="LanguageProficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Elementary Proficiency"),
                            (2, "Limited Working Proficiency"),
                            (3, "Professional Working Proficiency"),
                            (4, "Full Professional Proficiency"),
                            (5, "Native / Bilingual Proficiency"),
                        ],
                        help_text="The proficiency level of the user in this language.",
                    ),
                ),
                (
                    "lang",
                    models.ForeignKey(
                        help_text="The language in which the user has proficiency.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proficiencies",
                        to="languages.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Language Proficiency",
                "verbose_name_plural": "Language Proficiencies",
            },
        ),
    ]
